# The documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements" # file?
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "dependencies update:"
    target-branch: "develop"
