# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  # commands:
  #   - pip install -e .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - requirements: env/pip_prod.txt
    - requirements: env/pip_dev.txt
    - method: pip
      path: .

submodules:
  recursive: false
