# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  # commands:
  #   - pip install -e .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    - requirements: requirements/production.txt
    - requirements: requirements/develop.txt
    - method: pip
      path: .

submodules:
  recursive: false
