import network_diffusion.flat_spreading as FlatSpreading
from network_diffusion.multi_spreading import MultiSpreading
from network_diffusion.multilayer_network import MultilayerNetwork
from network_diffusion.propagation_model import PropagationModel
