name: Build and upload Client Package

on:
  push:
    branches: [package-simplification]
  pull_request:
    branches: [package-simplification]

jobs:
  Check-Quality-Of-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/production.txt
          pip install -r requirements/develop.txt
      - name: Validate
        run: |
          pre-commit install --config submodules/template-python/.pre-commit-config.yaml
          pre-commit run --all-files --config submodules/template-python/.pre-commit-config.yaml
      - name: Compute coverage
        run: |
          coverage run -m unittest discover
          bash <(curl -s https://codecov.io/bash)

# Build-Package:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Build for PyPI
#       run: python setup.py sdist bdist_wheel
#     - name: Build for Anaconda
#       run: ddd
# Publish package
# build package
# send to pypi
# send to conda
# push tag
# deploy:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Publish package
#       uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#       with:
#         user: __token__
#         password: ${{ secrets.PYPI_API_TOKEN }}
