name: package builds

on:
  push:
    branches: [package-simplification]

jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/production.txt
          pip install -r requirements/develop.txt
      - name: Build for PyPI
        run: python setup.py sdist bdist_wheel
      - name: Save artifacts
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./dist
  Publish-Package:
    runs-on: ubuntu-latest
    needs: [Build-Package]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: build
          path: ./dist
      - name: Publishing to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  Create-Tag-Release:
    runs-on: ubuntu-latest
    needs: [Build-Package]
    env:
      VER: Nil
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Obtain version
        run: |
          _VER=$(cat network_diffusion/__init__.py | grep __version__ | cut -d'"' -f2)
          echo "VER=${_VER}" >> $GITHUB_ENV
      - name: Add tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VER }}
          message: "Added tag"
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: build
          path: ./dist
      - name: Add GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VER }}
          files: |
            dist/*.whl
            dist/*.tar.gz
